version: "3.3"
services:
  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "api"
    restart: always
    ports:
      - "8083:8000"
    volumes:
      - ./swagger/user_ui.json:/user_ui.json
    command: /user_ui.json
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.{{.Name}}
    depends_on:
      - "fluentd"
  fluentd:
    image: cheungpat/fluentd-s3
    container_name: "fluented-s3"
    restart: always
    environment:
      - 'FLUENTD_CONF=fluent.conf'
    volumes:
      - ./fluentd:/fluentd/etc
    ports:
      - "24224:24224"
    logging:
      driver: "json-file"
networks:
  swagger_link:
    external: true
